//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pract1_Florich_I223.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int id_prod { get; set; }
        public string name_prod { get; set; }
        public string description_prod { get; set; }
        public decimal price_prod { get; set; }
        public Nullable<int> kolvo { get; set; }
        public string is_active { get; set; }
        public Nullable<int> category_id { get; set; }
    }
}
