//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pract1_Florich_I223.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string login_u { get; set; }
        public string pass_u { get; set; }
        public string email_u { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string is_active { get; set; }
        public string role { get; set; }
    }
}
